### PR TITLE
Use eslint-plugin-total-functions

### PR DESCRIPTION
**Pull request by danielnixon**

### CODE REVIEW

**Comment by NoxHarmonium** [comment]
Are the exceptions you put in due to limitations in the plugin or are they things we should fix? If it is the latter I might push up a commit to make the linter happy.

**Comment by danielnixon** [comment]
I believe I fixed all the false positives in the plugin, so these are all just grandfathered in.

**Comment by danielnixon** [comment]
Although https://github.com/danielnixon/eslint-plugin-total-functions/issues/11 would remove the need for at least one.

**Comment by danielnixon** [comment]
And https://github.com/danielnixon/eslint-plugin-total-functions/issues/18 would probably help too

**Comment by NoxHarmonium** [comment]
I don't have time to fix these issues right now so I've raised https://github.com/NoxHarmonium/peoples-choice/issues/19 and will merge this.

**Pull request merged**
